Sentiment analysis - movies review classification

**Import data**

In [3]:
import pandas as pd

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [6]:
url = "https://raw.githubusercontent.com/PyRPy/ML_Py_Templates/master/DataCamp_Templates_Py/Data/IMDB_sample.csv"

In [7]:
reviews = pd.read_csv(url)
reviews.head()

   Unnamed: 0                                             review  label
0       18245  This short spoof can be found on Elite's Mille...      0
1       19801  A singularly unfunny musical comedy that artif...      0
2        3222  An excellent series, masterfully acted and dir...      1
3        6010  The master of movie spectacle Cecil B. De Mill...      1
4       16355  I was gifted with this movie as it had such a ...      0

**Convert text/words to vectors**

In [8]:
vect = TfidfVectorizer(stop_words=ENGLISH_STOP_WORDS, ngram_range=(1, 2), 
        max_features=200, token_pattern=r'\b[^\d\W][^\d\W]+\b').fit(reviews.review)

In [9]:
X = vect.transform(reviews.review)

In [13]:
reviews_transformed = pd.DataFrame(X.toarray(), columns=vect.get_feature_names())
reviews_transformed.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

     acting    action  actor    actors  ...  worth      year  years     young
0  0.000000  0.000000    0.0  0.000000  ...    0.0  0.000000    0.0  0.000000
1  0.070525  0.000000    0.0  0.082068  ...    0.0  0.199219    0.0  0.000000
2  0.000000  0.000000    0.0  0.000000  ...    0.0  0.000000    0.0  0.292340
3  0.000000  0.217319    0.0  0.000000  ...    0.0  0.000000    0.0  0.208256
4  0.000000  0.114076    0.0  0.000000  ...    0.0  0.000000    0.0  0.000000

[5 rows x 200 columns]

**Prepare the label**

In [9]:
y = reviews.label

**Split the data into train and test sets**

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=456)

**Select and fit the model**

In [13]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression()

**Prediction and model evaluation**

In [14]:
y_pred = log_reg.predict(X_test)

In [16]:
print('Accuracy on the test data: ', accuracy_score(y_test, y_pred))

Accuracy on the test data:  0.7681545636242505

Confusion matrix

In [19]:
print(confusion_matrix(y_test, y_pred))

[[588 175]
 [173 565]]